### ISSUE TITLE
Case & benchmarking tab: LI gap visual needs adjustments

### ISSUE THREAD

**Issue by Tmlaan** [akvo/idh-ipd#67]
- [x] the red line should be above the blue bar, at actual income level. The label should show the actual income (net income from focus crop + non focus crop income) For example in CDI / cocoa/ company 5, the actual income red line should be at 2615. 
- [x] The gap in the visual should show the nominal figures in USD in the bar chart (this case 2,736) and the box next to the visual should show the LI gap % ( 51% for this case). This means all figures in the visual are in nominal amounts and next to the table we show 2 percentages: 1) % LI gap and 2) % of actual income from focus crop
- [x] round up figures to whole numbers (for all percentages in the dashboard)

**Comment by Tmlaan** [comment]
@dedenbangkit , one last comment here: the label of the red line at actual income should show the value of the actual income (total value of green + blue ); currently it shows the value of the living income gap

**Comment by dedenbangkit** [comment]
@Tmlaan which visualisation are you talking about? we have two red line there, the living income benchmark and total of green and blue (total income)

**Comment by Tmlaan** [comment]
@dedenbangkit I am referring to the lower red line with the text 'actual household income' . The text next to the line is correct, but the text box (when you hoover over it) is showing the text 'living wage gap' and the living wage gap value, instead of the actual household income Text and value
