### ISSUE TITLE
benchmarking page: 2 additional download options 

### ISSUE THREAD

**Issue by Tmlaan** [akvo/idh-ipd#70]
add 2 additional download options: 

- [x] download 5 graphs at bottom (income drivers) together in one visual 
- [x] download full page in one visual

**Comment by Tmlaan** [comment]
Deden, please put this on hold for now. We'll try to push back on this.

**Comment by dedenbangkit** [comment]
@Tmlaan no worries, I found a [library](https://www.npmjs.com/package/html-to-image) to reduce the complexity.
