### ISSUE TITLE
benchmarking page: add general introduction text

### ISSUE THREAD

**Issue by Tmlaan** [akvo/idh-ipd#72]
Include an introduction text at the top of the benchmarking page: "The averages used for benchmarking on this page reflect the average values of the companies included in this data set, for that specific sector and country".

**Comment by dedenbangkit** [comment]
@Tmlaan please check and confirm

**Comment by Tmlaan** [comment]
@dedenbangkit could we include this text in the textbook with metadata? see issue 74?

**Comment by dedenbangkit** [comment]
I have tried to combine this text with [metadata info](#74 ) but it looks ugly. So I separated them under the company general info.

**Comment by Tmlaan** [comment]
@dedenbangkit thank you, I like how the outline looks now with the meta data. One final comment from IDH: they asked to include 2 more details (dummy text) in the metadata information box: 

- [ ] on case page: add "Project / Coalition name(s): Beyond Chocolate"
- [ ] on both case & benchmark pages: add more benchmark info (use text "Benchmark: Cote d'Ivoire, Rural cocoa growing areas, Anker method/CIRES, 2018" instead of "Benchmark: 2018" .
