### ISSUE TITLE
Include text box with metadata (information about the data)

### ISSUE THREAD

**Issue by Tmlaan** [akvo/idh-ipd#74]
- [x] Include text box with metadata in the case/company page:

- Number farmer HH = 500; 
- Number of datasets included = 1; 
- Actual data (year): 2020; 
- Benchmark (year): 2018

- [x] Include text box with metadata in the benchmarking page:

- Actual data (year): 2020
- Benchmark (year): 2018
- Sector average (year): 2019, 2020
- Number companies considered in sector average: 2

**Comment by dedenbangkit** [comment]
Hi @Tmlaan what do you mean by companies considered in sector average: 2?

**Comment by Tmlaan** [comment]
Hi Deden, this means that the sector average value is calculated based on 2 companies. It is just dummy information, in a next version this information should come from the database

**Comment by Tmlaan** [comment]
@dedenbangkit somehow the text formatting is changing; it should just all be the same format (a list in a box)

**Comment by Tmlaan** [comment]
@dedenbangkit thank you, I like how the outline looks now with the meta data. One final comment from IDH: they asked to include 2 more details (dummy text) in the metadata information box:

- [ ]  on case page: add "Project / Coalition name(s): Beyond Chocolate"
- [ ]   on both case & benchmark pages: add more benchmark info (use text "Benchmark: Cote d'Ivoire, Rural cocoa growing 

areas, Anker method/CIRES, 2018" instead of "Benchmark: 2018" .
