### ISSUE TITLE
Benchmarking page: Income driver visuals

### ISSUE THREAD

**Issue by Tmlaan** [akvo/idh-ipd#80]
- [x] some text along the y axis and x axis got lost, could you please check what happened?

**Comment by dedenbangkit** [comment]
Could you please provide screenshot of the first case?

**Comment by Tmlaan** [comment]
![Screenshot 2021-09-17 at 11 05 18](https://user-images.githubusercontent.com/90041624/133756613-2fffc441-5bb1-4039-8d27-e94b1cd7bc5f.png)
